environment:
  image: Visual Studio 2017
  nodejs_version: "Stable"
  global:
    CYG_ROOT: C:/cygwin64
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin64/var/cache/setup

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm install -g esy
  - esy install

test_script:
  - esy make build
  - esy make test

# don't build? what does this do?
build: off
